### PR TITLE
Update ch6.md : forgotted coloring to js code.

### PR DESCRIPTION
**Pull request by syzer**

### CODE REVIEW

**Comment by syzer** [comment]
also HUGE +1 for this book :)

**Comment by DrBoolean** [comment]
Thanks!

**Comment by syzer** [comment]
No.. thank you.
Do you think would be nice to show ppl how to use react.js, or any more common framework to make a website?

**Comment by DrBoolean** [comment]
It is definitely a good idea. I hope to end each part with an example application. React is a great candidate for the next one.

**Pull request merged**
