### PR TITLE
Merge pull request #1 from DrBoolean/master

### PR DESCRIPTION
**Pull request by mike-on-github**
Pulling from origin

### CODE REVIEW

**Comment by jirutka** [comment]
@mike-on-github What the hell is this crap? Why are you repeatedly opening and immediately closing empty pull requests like this one? This is the third time.

**Comment by zerkms** [comment]
@jirutka I'm sure they have issues with getting how to deal with git/github

**Comment by jirutka** [comment]
It looks so, but I can’t imagine what’s he doing that he (probably) unintentionally produces these PRs instead of pulling origin. :confused:

**Comment by Ryan1729** [comment]
I would guess clicking a button that says "pull request" thinking that a pull request is asking someone to let them pull from the repo, not what it actually is: asking someone to pull some of your code into the repo.

**Comment by mike-on-github** [comment]
Sorry, I'm new to Github. Was trying to update my fork of this repo. Won't happen again.

**Comment by tonyday** [comment]
@mike-on-github 
I would not worry too much - newbies like you and me are allowed to make a few mistakes as we figure out what we are doing :-)
BTW I think that you picked a great repo to follow - I am learning heaps and enjoying it immensely.

**Pull request closed without merging**
